
server:
  port: 8281
  servlet.context-path: /goods

logging.level:
  root: @logging.level@
  com.bestaone: @logging.level@

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: @goods.database.url@
  username: @goods.database.username@
  password: @goods.database.password@

spring.session.store-type: none

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bestaone.himall.goods.domain

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  autoRuntimeDialect: true
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false
  returnPageInfo: true
  params: count=countSql

spring.jackson:
  default-property-inclusion: non_null
  serialization.write-dates-as-timestamps: true

himall.monitor.enable: true