
server:
  port: 8182
  servlet.context-path: /himall

logging.level:
  root: @logging.level@
  com.bestaone: @logging.level@

# 不配的话，打成jar无法访问页面
spring.thymeleaf:
    cache: true
    prefix: classpath:/templates
    mode: HTML5

security.oauth2:
  hiAuth:
    client:
      clientId: @hiauth.auth.clientId@
      clientSecret: @hiauth.auth.clientSecret@
      accessTokenUri: @hiauth.auth.accessTokenUri@
      userAuthorizationUri: @hiauth.auth.userAuthorizationUri@
      revokeTokenUri: @hiauth.auth.revokeTokenUri@
      clientAuthenticationScheme: form
    resource:
      userInfoUri: @hiauth.auth.userInfoUri@

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ServerListRefreshInterval: 2000
  ConnectTimeout: 3000
  ReadTimeout: 3000
  EnablePrimeConnections: false

order-svr.ribbon.listOfServers: @hiMall.microsvr.order.servers@
goods-svr.ribbon.listOfServers: @hiMall.microsvr.goods.servers@

hiMall.oAuth2.callbackUrl: @hiMall.oAuth2.callbackUrl@